dateModified: 1755709123
email:
  fromEmail: tim.hamilton6@gmail.com
  fromName: 'Tim Hamilton'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    12f6bb5d-8a2e-4602-a62f-1990b1f8f61e: 'Tim Hamilton' # Tim Hamilton
    c2201965-2e50-49ed-b4aa-c4a65f170838: 'Tim Hamilton' # Tim Hamilton
plugins:
  copy:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: solo
  live: true
  name: 'Tim Hamilton'
  schemaVersion: 5.8.0.3
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
